version: '3'
services:
    es:
        image: elasticsearch:2.2.1
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
    webapp:
        build: ./webapp
        links:
            - es
        depends_on:
            - es
        ports:
          - 7575:7575
        environment:
          - ELASTICSEARCH_PORT=9200
          - ELASTICSEARCH_HOST=es

    indexer:
        build: ./indexer
        command: "bash -c 'bundle exec ruby -Ilib bin/hdo-transcript-indexer -d `pwd`/data/'"
        volumes:
            - ./data:/code/data
        links:
            - es
        depends_on:
            - es
        environment:
          - ELASTICSEARCH_PORT=9200
          - ELASTICSEARCH_HOST=es
          - ELASTICSEARCH_URL=http://es:9200
