#!/bin/bash

set -x

DEPLOY_COMMAND="cd /webapps/hdo-transcript-search && git pull --ff-only origin master && cd webapp && npm run build && mkdir -p tmp && touch tmp/restart.txt"

if [[ -n "$TRAVIS" ]]; then
  touch scripts/deploy_dsa && chmod 0600 scripts/deploy_dsa && openssl aes-256-cbc -K $encrypted_c0905604faef_key -iv $encrypted_c0905604faef_iv -in scripts/deploy.enc -out scripts/deploy_dsa -d
  ssh -i scripts/deploy_dsa hdo@tale.holderdeord.no $DEPLOY_COMMAND
else
  ssh hdo@tale.holderdeord.no $DEPLOY_COMMAND
fi

